// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMagnet(arg1:string,arg2:string):Promise<string>;

export function AddTorrentFile(arg1:string,arg2:string):Promise<string>;

export function GetTorrents():Promise<Array<main.TorrentStatus>>;

export function PauseTorrent(arg1:string):Promise<void>;

export function RemoveTorrent(arg1:string):Promise<void>;

export function ResumeTorrent(arg1:string):Promise<void>;

export function SelectOutputFolder():Promise<string>;

export function SelectTorrentFile():Promise<string>;
