// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMagnet(arg1, arg2) {
  return window['go']['main']['App']['AddMagnet'](arg1, arg2);
}

export function AddTorrentFile(arg1, arg2) {
  return window['go']['main']['App']['AddTorrentFile'](arg1, arg2);
}

export function GetTorrents() {
  return window['go']['main']['App']['GetTorrents']();
}

export function RemoveTorrent(arg1) {
  return window['go']['main']['App']['RemoveTorrent'](arg1);
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function SelectTorrentFile() {
  return window['go']['main']['App']['SelectTorrentFile']();
}
